# Generated by Django 2.1.5 on 2019-02-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_myprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('contents', models.TextField()),
                ('image', models.FileField(upload_to='documents/About/img/')),
            ],
        ),
    ]
