# Generated by Django 2.1.5 on 2019-02-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_timeline_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subtitle', models.CharField(max_length=200)),
                ('subContents', models.TextField()),
                ('imageURLGit', models.TextField()),
            ],
        ),
    ]
