# Generated by Django 2.1.5 on 2019-02-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='genre',
            field=models.CharField(choices=[('CL', 'C language'), ('CP', 'Cpp'), ('JV', 'Java'), ('PY', 'Python'), ('ES', 'Else')], default='CL', max_length=2),
        ),
    ]
