# Generated by Django 2.1.5 on 2019-02-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_projects_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.DateField(help_text='ex) 2017-02-28'),
        ),
    ]
