# Generated by Django 2.1.5 on 2019-02-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20190218_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='genre',
            new_name='language',
        ),
    ]
