# Generated by Django 2.1.5 on 2019-02-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_projects_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='mainContents',
            field=models.TextField(null=True),
        ),
    ]
