# Generated by Django 2.1.5 on 2019-02-19 11:33

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_projects_maincontents'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='con',
            field=markdownx.models.MarkdownxField(default=0),
            preserve_default=False,
        ),
    ]
