# Generated by Django 2.1.5 on 2019-02-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_projects_con'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='mainContents',
        ),
    ]
