# Generated by Django 2.1.5 on 2019-02-19 11:53

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_projects_maincontents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='con',
            field=markdownx.models.MarkdownxField(help_text='* 보여질 내용물 : markdown으로 작성'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='imageURLGit',
            field=models.TextField(help_text='* 썸네일 사진 : 사진 직접 올리지말고 url을 올림'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='subContents',
            field=models.TextField(help_text='썸네일과 함께 보여질 간략한 내용'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='subtitle',
            field=models.CharField(help_text='썸네일과 함께 보여질 제목', max_length=200),
        ),
    ]
