# Generated by Django 2.1.5 on 2019-02-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20190219_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='imageURLGit',
            field=models.TextField(default='https://user-images.githubusercontent.com/34915108/53049248-069d5580-34da-11e9-81be-d683105b0f7d.gif', help_text='* 썸네일 사진 : 사진 직접 올리지말고 url을 올림'),
        ),
    ]
