# Generated by Django 2.1.7 on 2019-05-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20190221_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='show_public',
            field=models.BooleanField(default=True),
        ),
    ]
