# Generated by Django 2.1.7 on 2019-07-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_projects_show_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sep', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=200)),
            ],
        ),
    ]
